Tue, 29 Nov 2022 18:30:10 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:30:10 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:30:16 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | [27291] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:16 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | DISCONNECT
Tue, 29 Nov 2022 18:30:17 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | [27293] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:18 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | DISCONNECT
Tue, 29 Nov 2022 18:30:19 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | [27295] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:19 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | DISCONNECT
Tue, 29 Nov 2022 18:30:20 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | [27297] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:20 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | DISCONNECT
Tue, 29 Nov 2022 18:30:23 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:30:23 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:30:25 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | [27312] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:26 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | DISCONNECT
Tue, 29 Nov 2022 18:30:26 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | [27314] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:27 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | DISCONNECT
Tue, 29 Nov 2022 18:30:27 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | [27316] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:28 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | DISCONNECT
Tue, 29 Nov 2022 18:30:29 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:30:29 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:30:32 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | [27331] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:33 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | DISCONNECT
Tue, 29 Nov 2022 18:30:34 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | [27333] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:35 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | DISCONNECT
Tue, 29 Nov 2022 18:31:31 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | [27340] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:31:32 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | DISCONNECT
Tue, 29 Nov 2022 18:31:47 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS16 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:31:47 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:31:48 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717908539217800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:31:49 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717908539217800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27356' | DISCONNECT
Tue, 29 Nov 2022 18:31:58 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "serial/serialposix.py", line 322, in open
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | OSError: [Errno 5] Input/output error: '/dev/ttyS16'
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | 
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | During handling of the above exception, another exception occurred:
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | 
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "serial/serialposix.py", line 325, in open
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | serial.serialutil.SerialException: [Errno 5] could not open port /dev/ttyS16: [Errno 5] Input/output error: '/dev/ttyS16'
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | [27360] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:31:59 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | DISCONNECT
Tue, 29 Nov 2022 18:32:02 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:32:02 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:32:03 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 483, in command
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 446, in write
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "serial/serialposix.py", line 663, in write
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | serial.serialutil.SerialTimeoutException: Write timeout
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | [27375] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:32:18 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | DISCONNECT
Tue, 29 Nov 2022 18:34:43 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 483, in command
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 446, in write
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "serial/serialposix.py", line 663, in write
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | serial.serialutil.SerialTimeoutException: Write timeout
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | [27384] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:34:58 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | DISCONNECT
Tue, 29 Nov 2022 18:37:50 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718270320880800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:38:49 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:38:49 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:38:50 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 483, in command
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 446, in write
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "serial/serialposix.py", line 663, in write
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | serial.serialutil.SerialTimeoutException: Write timeout
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | [27477] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:39:05 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | DISCONNECT
Tue, 29 Nov 2022 18:41:53 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 493, in command
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' |   File "esptool.py", line 438, in read
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' | StopIteration
Tue, 29 Nov 2022 18:42:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' | [27483] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:42:01 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718513229386800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27482' | DISCONNECT
Tue, 29 Nov 2022 18:44:14 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 483, in command
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "esptool.py", line 446, in write
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' |   File "serial/serialposix.py", line 663, in write
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' | serial.serialutil.SerialTimeoutException: Write timeout
Tue, 29 Nov 2022 18:44:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' | [27508] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:44:28 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718654496055300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27507' | DISCONNECT
Tue, 29 Nov 2022 18:44:52 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:44:52 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:44:56 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718696051958500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:45:34 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718696051958500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27521' | DISCONNECT
Wed, 30 Nov 2022 09:55:20 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 09:55:20 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 09:55:41 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 09:55:41 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 09:55:44 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773344231854700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:55:52 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773344231854700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27730' | DISCONNECT
Wed, 30 Nov 2022 09:56:03 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773363166666600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:56:11 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773363166666600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27733' | DISCONNECT
Wed, 30 Nov 2022 09:56:34 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:56:34 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' | [27739] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:56:34 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773394188527700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27738' | DISCONNECT
Wed, 30 Nov 2022 09:56:49 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:56:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' | [27742] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:56:49 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773409066700500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27741' | DISCONNECT
Wed, 30 Nov 2022 09:56:55 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 09:56:55 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 09:56:57 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:56:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' | [27757] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:56:58 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773417744426900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27755' | DISCONNECT
Wed, 30 Nov 2022 09:57:30 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:57:31 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' | [27759] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:57:31 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773450841235800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27758' | DISCONNECT
Wed, 30 Nov 2022 09:57:51 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:57:51 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' | [27761] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:57:51 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773471011605300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27760' | DISCONNECT
Wed, 30 Nov 2022 09:58:21 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 09:58:21 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 09:58:24 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:58:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' | [27776] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:58:25 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773504526853600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27774' | DISCONNECT
Wed, 30 Nov 2022 09:58:49 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:58:50 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' | [27798] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:58:50 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773529629145300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27797' | DISCONNECT
Wed, 30 Nov 2022 09:58:58 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:58:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' | [27801] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:58:59 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773538955937200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27800' | DISCONNECT
Wed, 30 Nov 2022 09:59:09 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:59:09 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' | [27805] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:59:09 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773549132270600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27804' | DISCONNECT
Wed, 30 Nov 2022 09:59:15 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:59:15 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' | [27807] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:59:15 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773555216113500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27806' | DISCONNECT
Wed, 30 Nov 2022 09:59:43 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' | Traceback (most recent call last):
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "esptool.py", line 5482, in <module>
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "esptool.py", line 5475, in _main
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "esptool.py", line 4782, in main
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "esptool.py", line 111, in get_default_connected_device
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "esptool.py", line 388, in detect_chip
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "esptool.py", line 345, in __init__
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 09:59:43 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' | [27809] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 09:59:43 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669773583076532300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27808' | DISCONNECT
Wed, 30 Nov 2022 10:08:37 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 10:08:37 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 10:08:44 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 10:08:44 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 10:08:48 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' | Traceback (most recent call last):
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "esptool.py", line 34, in <module>
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "esptool/__init__.py", line 1026, in _main
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "esptool/__init__.py", line 666, in main
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "esptool/__init__.py", line 909, in get_default_connected_device
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "esptool/cmds.py", line 90, in detect_chip
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "esptool/loader.py", line 273, in __init__
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "serial/__init__.py", line 90, in serial_for_url
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "serial/serialposix.py", line 332, in open
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' | termios.error: (5, 'Input/output error')
Wed, 30 Nov 2022 10:08:49 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' | [27974] Failed to execute script 'esptool' due to unhandled exception!
Wed, 30 Nov 2022 10:08:49 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669774128454939400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27972' | DISCONNECT
Wed, 30 Nov 2022 18:23:47 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:23:47 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:24:34 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:24:34 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:24:37 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669803877770458200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 18:25:16 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669803877770458200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'53' | DISCONNECT
Wed, 30 Nov 2022 18:26:24 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669803984709416100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:26:24 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:26:24 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:26:33 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669803993705285500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:26:33 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:26:33 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:27:49 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804069989220600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:27:49 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:27:49 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:27:56 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804076077943800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Wed, 30 Nov 2022 18:28:34 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804076077943800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'99' | DISCONNECT
Wed, 30 Nov 2022 18:28:40 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804120455343600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:28:40 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:28:40 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:28:52 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804132795181000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:28:52 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:28:52 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:28:58 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804138684576300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:28:58 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:28:58 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:30:37 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:30:37 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:30:38 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804238695144400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:31:16 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804238695144400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'158' | DISCONNECT
Wed, 30 Nov 2022 18:37:50 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:37:50 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:37:57 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:37:57 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:37:57 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804677875222500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:38:36 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804677875222500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'185' | DISCONNECT
Wed, 30 Nov 2022 18:39:55 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:39:55 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:39:56 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804796343236100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:40:34 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804796343236100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'200' | DISCONNECT
Wed, 30 Nov 2022 18:41:55 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:41:55 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:41:59 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:41:59 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:42:00 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804920348632600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:42:38 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804920348632600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'227' | DISCONNECT
Wed, 30 Nov 2022 18:42:57 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:42:57 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:43:01 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:43:01 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:43:02 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804982598603800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:43:40 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669804982598603800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'254' | DISCONNECT
Wed, 30 Nov 2022 18:46:36 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:46:36 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:46:41 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:46:41 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:46:41 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669805201937478600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:47:20 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669805201937478600' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'281' | DISCONNECT
Wed, 30 Nov 2022 18:56:10 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:56:10 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:56:37 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:56:37 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:56:39 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669805799371791900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:57:17 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669805799371791900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'308' | DISCONNECT
Wed, 30 Nov 2022 18:57:25 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Wed, 30 Nov 2022 18:57:25 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Wed, 30 Nov 2022 18:57:25 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669805845995323500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Wed, 30 Nov 2022 18:58:04 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669805845995323500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'323' | DISCONNECT
Thu, 01 Dec 2022 09:05:49 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:05:49 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:05:51 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669856751621083800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:06:29 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669856751621083800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'341' | DISCONNECT
Thu, 01 Dec 2022 09:06:39 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:06:39 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:06:40 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669856800552926400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:07:18 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669856800552926400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'356' | DISCONNECT
Thu, 01 Dec 2022 09:12:02 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:12:02 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:12:02 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857122789045700' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:12:41 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857122789045700' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'371' | DISCONNECT
Thu, 01 Dec 2022 09:13:21 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:13:21 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:13:22 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857202154719700' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:14:00 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857202154719700' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'386' | DISCONNECT
Thu, 01 Dec 2022 09:19:30 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:19:30 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:19:31 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857571139274400' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:20:09 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857571139274400' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'401' | DISCONNECT
Thu, 01 Dec 2022 09:20:35 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:20:35 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:20:35 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857635811097200' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:21:22 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669857635811097200' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'416' | DISCONNECT
Thu, 01 Dec 2022 09:44:07 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:44:07 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:44:07 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859047757709800' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:44:45 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859047757709800' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'433' | DISCONNECT
Thu, 01 Dec 2022 09:54:02 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:54:02 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:54:02 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' | Traceback (most recent call last):
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "esptool.py", line 34, in <module>
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "esptool/__init__.py", line 1026, in _main
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "esptool/__init__.py", line 666, in main
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "esptool/__init__.py", line 909, in get_default_connected_device
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "esptool/cmds.py", line 90, in detect_chip
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "esptool/loader.py", line 283, in __init__
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "esptool/loader.py", line 299, in _set_port_baudrate
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "serial/serialutil.py", line 299, in baudrate
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' | termios.error: (5, 'Input/output error')
Thu, 01 Dec 2022 09:54:02 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' | [449] Failed to execute script 'esptool' due to unhandled exception!
Thu, 01 Dec 2022 09:54:03 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859642394384500' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'447' | DISCONNECT
Thu, 01 Dec 2022 09:55:06 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:55:06 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:55:07 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' | Traceback (most recent call last):
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "esptool.py", line 34, in <module>
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "esptool/__init__.py", line 1026, in _main
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "esptool/__init__.py", line 666, in main
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "esptool/__init__.py", line 909, in get_default_connected_device
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "esptool/cmds.py", line 90, in detect_chip
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "esptool/loader.py", line 283, in __init__
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "esptool/loader.py", line 299, in _set_port_baudrate
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "serial/serialutil.py", line 299, in baudrate
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' | termios.error: (5, 'Input/output error')
Thu, 01 Dec 2022 09:55:07 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' | [464] Failed to execute script 'esptool' due to unhandled exception!
Thu, 01 Dec 2022 09:55:07 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859707092420300' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'462' | DISCONNECT
Thu, 01 Dec 2022 09:56:00 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:56:00 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:56:00 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' | Traceback (most recent call last):
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "esptool.py", line 34, in <module>
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "esptool/__init__.py", line 1026, in _main
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "esptool/__init__.py", line 666, in main
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "esptool/__init__.py", line 909, in get_default_connected_device
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "esptool/cmds.py", line 90, in detect_chip
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "esptool/loader.py", line 283, in __init__
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "esptool/loader.py", line 299, in _set_port_baudrate
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "serial/serialutil.py", line 299, in baudrate
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' | termios.error: (5, 'Input/output error')
Thu, 01 Dec 2022 09:56:01 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' | [484] Failed to execute script 'esptool' due to unhandled exception!
Thu, 01 Dec 2022 09:56:01 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859760438534000' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'482' | DISCONNECT
Thu, 01 Dec 2022 09:56:56 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 09:56:56 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 09:56:56 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' | CONNECT
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' | Traceback (most recent call last):
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "esptool.py", line 34, in <module>
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "esptool/__init__.py", line 1026, in _main
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "esptool/__init__.py", line 666, in main
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "esptool/__init__.py", line 909, in get_default_connected_device
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "esptool/cmds.py", line 90, in detect_chip
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "esptool/loader.py", line 283, in __init__
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "esptool/loader.py", line 299, in _set_port_baudrate
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "serial/serialutil.py", line 299, in baudrate
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' | termios.error: (5, 'Input/output error')
Thu, 01 Dec 2022 09:56:57 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' | [499] Failed to execute script 'esptool' due to unhandled exception!
Thu, 01 Dec 2022 09:56:57 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669859816823204100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost:8080' pid:'497' | DISCONNECT
Thu, 01 Dec 2022 11:18:51 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 11:18:51 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 11:18:52 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669864732113313100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost' | CONNECT
Thu, 01 Dec 2022 11:19:30 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669864732113313100' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost' pid:'5360' | DISCONNECT
Thu, 01 Dec 2022 11:20:47 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 11:20:47 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 11:20:47 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669864847976833900' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost' | CONNECT
Thu, 01 Dec 2022 11:21:26 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669864847976833900' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost' pid:'5375' | DISCONNECT
Thu, 01 Dec 2022 11:22:35 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool write_flash 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Thu, 01 Dec 2022 11:22:35 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Thu, 01 Dec 2022 11:22:36 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669864956114139600' remote:'127.0.0.1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://localhost' | CONNECT
